name: "CorpX Docu Deployment"

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      URL_CHECKER_TIMEOUT: 30
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: "Cache Node"
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      #- name: "Install dependencies"
      #  run: npm ci
      #  continue-on-error: false

      - name: "Run all the linters"
        run: npm run lint:all
        continue-on-error: false

      - name: "Run Scripts"
        run: node script/url-checker.js -t ${{ env.URL_CHECKER_TIMEOUT }}
        continue-on-error: false
        
